# Generated by Django 4.2.13 on 2024-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
