# Generated by Django 4.2.13 on 2024-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0002_remove_tag_description_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
