# Generated by Django 4.2.13 on 2024-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0003_quest_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
