# Generated by Django 4.2.13 on 2024-06-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0004_alter_quest_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="done",
        ),
    ]
