# Generated by Django 4.2.13 on 2024-06-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0006_ticket_ticketissuance_ticket_issued_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
