# Generated by Django 4.2.13 on 2024-06-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0011_report_done_quest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="done_quest",
        ),
    ]
