# Generated by Django 4.2.13 on 2024-07-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0012_remove_report_done_quest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest",
            old_name="reward",
            new_name="badget",
        ),
    ]
