# Generated by Django 4.2.13 on 2024-07-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0013_rename_reward_quest_badget"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="exampleUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="imgUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
