# Generated by Django 4.2.13 on 2024-07-16 16:53

from django.db import migrations, models
import quests.models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0015_questcompletion_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="badget",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="exampleUrl",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="imgUrl",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="location",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="questcompletion",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to=quests.models.PathAndRename("media")
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
