# Generated by Django 4.2.13 on 2024-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0016_alter_quest_badget_alter_quest_exampleurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
