# Generated by Django 4.2.13 on 2024-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0017_alter_tag_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
