# Generated by Django 4.2.13 on 2024-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0022_savedquest"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quest",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
