# Generated by Django 4.2.13 on 2024-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0023_quest_latitude_quest_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="tips",
            field=models.TextField(blank=True, null=True),
        ),
    ]
