# Generated by Django 4.2.19 on 2025-02-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0024_quest_tips"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="issued_to",
        ),
        migrations.RemoveField(
            model_name="ticketissuance",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="ticketissuance",
            name="user",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="TicketIssuance",
        ),
    ]
