# Generated by Django 4.2.19 on 2025-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="level"
            ),
        ),
    ]
